version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - ADMIN_TOKEN
      - WEBSOCKET_ENABLED=true
    networks:
      - traefik
    volumes:
      - ./vw-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden.rule=Host(`${HOST}`)"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.services.vaultwarden-ws.loadbalancer.server.port=3012"
      - "traefik.http.routers.vaultwarden-ws.rule=Host(`${HOST}`) &&
        PathPrefix(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-ws.service=vaultwarden-ws"

networks:
  traefik:
    external: true
